# Generated by Django 5.2.8 on 2025-12-06 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome / Bootstrap icon class', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_tagline', models.CharField(blank=True, max_length=150)),
                ('default_about', models.TextField(blank=True)),
                ('default_email', models.EmailField(blank=True, max_length=254)),
                ('default_instagram', models.CharField(blank=True, max_length=200)),
                ('default_twitter', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('about', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('project1_title', models.CharField(blank=True, max_length=120)),
                ('project1_description', models.TextField(blank=True)),
                ('project1_url', models.URLField(blank=True)),
                ('project2_title', models.CharField(blank=True, max_length=120)),
                ('project2_description', models.TextField(blank=True)),
                ('project2_url', models.URLField(blank=True)),
                ('project3_title', models.CharField(blank=True, max_length=120)),
                ('project3_description', models.TextField(blank=True)),
                ('project3_url', models.URLField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolios.portfoliotemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portfolios.portfolio')),
            ],
        ),
    ]
