# Generated by Django 5.2.8 on 2025-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='template_path',
            field=models.CharField(default='default_template.html', max_length=200),
            preserve_default=False,
        ),
    ]
