# Generated by Django 5.2.8 on 2025-12-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfoliotemplate_template_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotemplate',
            name='template_path',
            field=models.CharField(default='portfolios/templates_pack/arch_minimal.html', max_length=200),
        ),
    ]
