# Generated by Django 5.2.8 on 2025-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfoliotemplate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='tagline',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_about_me',
            field=models.TextField(default='A seasoned professional dedicated to crafting visually stunning and highly functional digital experiences.'),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_contact_email',
            field=models.EmailField(default='contact@samanthajdoe.com', max_length=254),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_full_name',
            field=models.CharField(default='Samantha J. Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_project_description',
            field=models.TextField(default='A sample project description to showcase the template layout.'),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_project_title',
            field=models.CharField(default='Sample Project', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_project_url',
            field=models.URLField(default='https://example.com', help_text='Example project link', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_tagline',
            field=models.CharField(default='Senior UX/UI Designer & Web Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='portfoliotemplate',
            name='template_path',
            field=models.CharField(default='portfolios/portfolio_template1.html', help_text='Path to the HTML template (use Django include)', max_length=255),
        ),
    ]
