# Generated by Django 5.2.8 on 2025-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfoliotemplate_template_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='preview_partial',
            field=models.CharField(default='', max_length=255),
        ),
    ]
