# Generated by Django 5.2.8 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_remove_portfoliotemplate_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='default_project_description',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='default_project_title',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='default_project_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects_json',
            field=models.JSONField(blank=True, default=list, help_text='List of projects in JSON format.'),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_projects_json',
            field=models.JSONField(default=list, help_text='Default list of projects for this template, in JSON format.'),
        ),
    ]
