# Generated by Django 5.2.8 on 2025-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_portfolio_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='projects_json',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='default_projects_json',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project1_description',
            field=models.TextField(blank=True, null=True, verbose_name='Project 1 Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project1_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project 1 Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project1_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Project 1 URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_description',
            field=models.TextField(blank=True, null=True, verbose_name='Project 2 Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project 2 Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Project 2 URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_description',
            field=models.TextField(blank=True, null=True, verbose_name='Project 3 Description'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project 3 Title'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Project 3 URL'),
        ),
    ]
