# Generated by Django 5.2.8 on 2025-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_remove_portfolio_projects_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='default_full_name',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_first_name',
            field=models.CharField(default='Samantha', max_length=50),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='default_last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
